Fixed requirements and test-requirements for zun tempest plugin
* Since tempest plugin does contains any unit tests that's why there
  will be no test dependency stay there and those will be moved
  to requirements.txt. The tempest plugin sanity check runned
  against tempest gate is also failing giving
  ImportError: No module named tempest_plugin.plugin.

  It can be fixed by fixing requirements for the plugin.
* https://review.openstack.org/#/c/514269/

Change-Id: I3de3d6c6928d31af9c2deeba800b201bb681ac4e